# Generated by Django 5.2.5 on 2025-09-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=50)),
                ('to_user', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('mail_content', models.CharField(max_length=4000)),
                ('datetime', models.DateTimeField()),
                ('attachment', models.FileField(blank=True, upload_to='attachments/')),
            ],
        ),
    ]
